---
- name: Enable root logon in sshd_config
  lineinfile: 
    path: /etc/ssh/sshd_config
    regexp: '.*PermitRootLogin.*'
    line: 'PermitRootLogin yes'

- name: Enable password authentication in sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '.*PasswordAuthentication.*'
    line: 'PasswordAuthentication yes'

- name: Restart sshd
  service:
    name: sshd
    state: restarted